In [65]:
import torch

In [66]:
torch.__version__

'1.12.0+cpu'

In [67]:
import numpy as np

In [68]:
a = np.array([1, 2])
a

array([1, 2])

In [69]:
a.dtype

dtype('int32')

In [70]:
t = torch.tensor(a)

In [71]:
t.dtype

torch.int32

In [72]:
t2 = torch.tensor([1, 2])

In [73]:
t2.dtype, t2

(torch.int64, tensor([1, 2]))

In [74]:
np.array(t2)

array([1, 2], dtype=int64)

In [75]:
f = np.array([1.1, 2.2])
f, f.dtype

(array([1.1, 2.2]), dtype('float64'))

In [76]:
torch.tensor(np.array([1.1, 2.2]))

tensor([1.1000, 2.2000], dtype=torch.float64)

In [77]:
 torch.tensor([1.1, 2.2]).dtype

torch.float32

In [78]:
b = torch.tensor([True, False])
b

tensor([ True, False])

In [79]:
b.dtype

torch.bool

In [80]:
x1 = torch.tensor(-3 + pow(3, 1/2) * 3j)
x2 = torch.tensor(-3 - pow(3, 1/2) * 3j)

In [81]:
x1 * x1 + 6 * x1 + 36

tensor(0.+0.j)

In [82]:
x2 * x2 + 6 * x2 + 36

tensor(0.+0.j)

In [83]:
x1*x1*x1, x2*x2*x2

(tensor(216.0000+1.5259e-05j), tensor(216.0000-1.5259e-05j))

In [84]:
t = torch.tensor([1.1])

In [85]:
t.dtype

torch.float32

In [86]:
t1 = torch.tensor([1, 2])

In [87]:
t1.ndim

1

In [88]:
t2 = torch.tensor([[1, 2], 
                   [3, 4]])

In [89]:
t2.ndim

2

In [90]:
t1.shape, t2.shape

(torch.Size([2]), torch.Size([2, 2]))

In [91]:
t2.numel()

4

In [92]:
t0 = torch.tensor(1)
t1 = torch.tensor([1])

In [93]:
t0, t1

(tensor(1), tensor([1]))

In [94]:
len(t0), len(t1)

TypeError: len() of a 0-d tensor

In [95]:
t0.shape, t1.shape

(torch.Size([]), torch.Size([1]))

In [96]:
t0.numel(), t1.numel()

(1, 1)

In [97]:
t1 = np.array([[1, 2, 3],
               [4, 5, 6]])

In [98]:
t1.shape

(2, 3)

In [99]:
t2 = np.array([[2,3,4],
               [3,4,5]])

In [100]:
t2.shape

(2, 3)

In [101]:
t3 = torch.tensor([t1, t2])

C:\Users\qidson01\AppData\Local\Temp\ipykernel_4724\3613564659.py:1: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_new.cpp:204.)
  t3 = torch.tensor([t1, t2])


In [102]:
t3.shape

torch.Size([2, 2, 3])

In [103]:
t3.ndim

3

In [104]:
t3.numel()

12

In [105]:
t4 = np.array([t1, t2])

In [106]:
t4.shape

(2, 2, 3)

In [107]:
t4 = t4.reshape(1, 1, 2, 6)
t4

array([[[[1, 2, 3, 4, 5, 6],
         [2, 3, 4, 3, 4, 5]]]])

In [108]:
t4.shape

(1, 1, 2, 6)

In [109]:
t4.reshape(-1).shape

(12,)

In [110]:
t4.flatten().shape

(12,)

In [178]:
a = torch.ones(3, 4)
b = torch.ones(3, 1)

In [179]:
torch.mul(a, b)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [134]:
torch.mm(a, b).shape

torch.Size([3, 2])

In [135]:
torch.matmul(a, b).shape

torch.Size([3, 2])

In [137]:
a1 = torch.ones(1, 3, 4)
a2 = torch.ones(1, 4, 2)
torch.bmm(a, b).shape

RuntimeError: batch1 must be a 3D tensor

In [139]:
c = 6
torch.mul(c, a).shape, torch.mul(a, c).shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [169]:
a = torch.ones([1, 2, 3])
d = torch.ones([4, 5, 6])
a, d, torch.tensor(a)

C:\Users\qidson01\AppData\Local\Temp\ipykernel_4724\2571802257.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  a, d, torch.tensor(a)


(tensor([[[1., 1., 1.],
          [1., 1., 1.]]]),
 tensor([[[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]]]),
 tensor([[[1., 1., 1.],
          [1., 1., 1.]]]))

In [170]:
import torch

# 创建两个输入张量
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

# 执行逐元素相乘操作
result = torch.mul(tensor1, tensor2)

# print(result)  # 输出: tensor([ 4, 10, 18])
tensor1

tensor([1, 2, 3])